name: Build

on:
  push:
    branches:
      - 'main'
      - 'dev'
  pull_request:

jobs:

  build-on-linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - run: python xx.py build-debug
    - run: python xx.py build-release
    - run: ./build/ja2vcp --unittests
    - run: ./build-release/ja2vcp --unittests

  build-on-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - run: python xx.py build-debug
    - run: python xx.py build-release
    - run: build\Debug\ja2vcp.exe --unittests
    - run: build\Release\ja2vcp.exe --unittests
